### ISSUE TITLE
Carregar do JabRef no SonarQube conforme tutorial

### ISSUE THREAD

**Issue by pedromigliatti** [SampaioFelipe/DC-UFSCar-ES2-201701-CepoDeMadeira#4]
https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Gradle

**Comment by SampaioFelipe** [comment]
Todos conseguiram realizar a integração

**Comment by whoisroot** [comment]
@SampaioFelipe quase todos...
